// ─── EvidencePackSummary ───────────────────────────────────────────
// Headline summary for a static external evidence pack.

import { Archive, Boxes } from "lucide-react";
import { MetricCell, ObsDivider, SectionLabel, StatusBadge } from "@/components/ui/ObsCommon";
import { evidencePackDomainRows, evidencePackFamilyRows } from "@/lib/evidence-pack/derived";
import type { ExternalEvidencePack } from "@/lib/evidence-pack/types";

export function EvidencePackSummary({ pack }: { pack: ExternalEvidencePack }) {
    const families = evidencePackFamilyRows(pack);
    const domains = evidencePackDomainRows(pack);

    return (
        <article className="obs-panel flex flex-col gap-5">
            <div className="flex items-start justify-between gap-4 flex-wrap">
                <div className="flex flex-col gap-2">
                    <div className="flex items-center gap-2 flex-wrap">
                        <span className="badge badge-signal">Evidence Pack</span>
                        <span className="badge badge-muted">{pack.sourceType}</span>
                    </div>
                    <h3 className="flex items-center gap-2 text-sm font-semibold text-text-primary">
                        <Archive className="h-4 w-4 text-text-muted" aria-hidden="true" />
                        {pack.repositoryLabel}
                    </h3>
                    <p className="text-[10px] font-mono text-text-muted">
                        {pack.packId} · {pack.schemaVersion} · generated by {pack.generatedBy}
                    </p>
                </div>
                <div className="flex flex-col items-end gap-1.5">
                    <span className="text-[10px] font-mono uppercase tracking-wider text-text-muted">Posture</span>
                    <StatusBadge label={pack.advisoryOnly ? "Advisory Only" : "Not Advisory"} variant={pack.advisoryOnly ? "muted" : "risk"} />
                    <StatusBadge label={pack.noRepositoryMutation ? "No Mutation" : "Mutation Risk"} variant={pack.noRepositoryMutation ? "verified" : "risk"} />
                </div>
            </div>

            <ObsDivider />

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-1">
                <MetricCell label="Files" value={pack.fileCount} />
                <MetricCell label="Edges" value={pack.edgeCount} />
                <MetricCell label="Routes" value={pack.routeCount} />
                <MetricCell label="Components" value={pack.componentCount} />
                <MetricCell label="Data Modules" value={pack.dataModuleCount} />
                <MetricCell label="Docs" value={pack.docsCount} />
                <MetricCell label="Unresolved" value={pack.unresolvedImportCount} />
                <MetricCell label="Consequence Edges" value={pack.consequenceBearingEdges.length} />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
                <div className="flex flex-col gap-2">
                    <SectionLabel>
                        <span className="inline-flex items-center gap-1.5">
                            <Boxes className="h-3 w-3" aria-hidden="true" /> File-family breakdown
                        </span>
                    </SectionLabel>
                    <div className="grid grid-cols-2 gap-2">
                        {families.map((row) => (
                            <div key={row.label} className="flex items-center justify-between gap-2 rounded-md border border-border-subtle bg-surface-elevated px-3 py-2">
                                <span className="text-xs font-mono text-text-secondary">{row.label}</span>
                                <span className="text-xs font-semibold text-text-primary">{row.count}</span>
                            </div>
                        ))}
                    </div>
                </div>
                <div className="flex flex-col gap-2">
                    <SectionLabel>Domain summary</SectionLabel>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {domains.map((row) => (
                            <div key={row.label} className="flex items-center justify-between gap-2 rounded-md border border-border-subtle bg-surface-elevated px-3 py-2">
                                <span className="text-xs font-mono text-text-secondary">{row.label}</span>
                                <span className="text-xs font-semibold text-text-primary">{row.count}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </article>
    );
}
